apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-scanner-parameters-configmap
data:
  kube-scanner-parameters.yaml: |-
    # Configuration values can be set as key-value properties
    parallelization: 10
    buffer: 1000

    kube:
      configPath: /usr/.kube/kubeconfig
      namespaces:
        - default
        - operations
    
    scanner:
      !trivy-scanner
      binaryPath: /usr/local/bin/trivy
      cachePath: /storage/.trivycache
      registries:
        - name: myacr.azurecr.io
          address: myacr.azurecr.io
          username: myacr
          password: <MYACRPASSWD>
        - name: deepnetwork
          address: http://registry.hub.docker.com
          username: 
          password: 
    
    exporter:
      !file-exporter
      path: /storage/scan-results/
    
    importer:
      !file-importer
      path: /storage/scan-results/