apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-scanner
  labels:
    app: kube-scanner
    module: kube-scanner
    version: '0.2'
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: kube-scanner
  template:
    metadata:
      labels:
        app: kube-scanner
        module: kube-scanner
        version: '0.2'
    spec:
      containers:
      - name: kube-scanner
        image: deepnetwork/kube-scanner-webapp:0.2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "200M"
            cpu: "500m"
          limits:
            memory: "500M"
            cpu: "1000m"
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /health/liveness
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        ports:
          - containerPort: 8080
            name: main-http
        securityContext:
          runAsUser: 10001
          runAsGroup: 10001
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          readOnlyRootFilesystem: false
        volumeMounts:
          - name: kube-config-file-volume
            mountPath: /usr/.kube
          - name: kube-scanner-parameters-volume
            mountPath: /kube-scanner
          - name: storage-volume
            mountPath: "/storage"
        env:
          - name: KUBE_SCANNER_CONFIG_FILE_PATH
            value: "/kube-scanner/kube-scanner-parameters.yaml"
      securityContext:
        fsGroup: 10001
      volumes:
        - name: kube-config-file-volume
          configMap:
            name: kube-config-file-configmap
            defaultMode: 0777
        - name: kube-scanner-parameters-volume
          configMap:
            name: kube-scanner-parameters-configmap
            defaultMode: 0777
        - name: storage-volume
          persistentVolumeClaim:
            claimName: kube-scanner-storage