apiVersion: v1
kind: Service
metadata:
  name: image-scanner
  labels:
    app: image-scanner
    module: image-scanner
spec:
  selector:
    app: image-scanner
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: main-http
  type: ClusterIP
