apiVersion: v1
kind: Service
metadata:
  name: kube-scanner
  labels:
    app: kube-scanner
    module: kube-scanner
spec:
  selector:
    app: kube-scanner
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
