name: ci-master

on: 
  push:
    branches:
    - master

jobs:
  build-n-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set env vars
      run: |
        base_tag=$(cat ./version)
        SHA8=$(echo $GITHUB_SHA | cut -c1-8)
        webapp_tag="deepnetwork/image-scanner-web:$base_tag-$SHA8"
        cliapp_tag="deepnetwork/image-scanner-cli:$base_tag-$SHA8"
        echo "::set-env name=WEBAPP_TAG::$webapp_tag"
        echo "::set-env name=CLIAPP_TAG::$cliapp_tag"

        tests_tag="deepnetwork/image-scanner:$base_tag-$SHA8-tests"
        tests_dir="$HOME/testresults"
        echo "::set-env name=TESTS_TAG::$tests_tag"
        echo "::set-env name=TESTS_DIR::$tests_dir"

    - name: run unit-tests
      run: |
        docker build -t ${{ env.TESTS_TAG }} -f ./dockerfile --target testrunner .
        sudo mkdir -p ${{ env.TESTS_DIR }}
        docker run --rm --mount type=bind,source=${{ env.TESTS_DIR }},target=/app/testresults ${{ env.TESTS_TAG }}

    - name: publish test results
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test_results
        path: '${{ env.TESTS_DIR }}/test_results.xml'

    - name: lint dockerfile
      uses: brpaz/hadolint-action@v1.0.2
      with:
        dockerfile: ./dockerfile

    - name: build ConsoleApp dockerimage
      run: |
        docker build -t ${{ env.CLIAPP_TAG }} -f ./dockerfile --target cliapp .

    - name: scan ConsoleApp for CVEs
      uses: 'docker://aquasec/trivy:0.2.1'
      with:
        args: --exit-code 1 --severity HIGH,CRITICAL ${{ env.CLIAPP_TAG }}

    - name: build WebApp dockerimage
      run: |
        docker build -t ${{ env.WEBAPP_TAG }} -f ./dockerfile --target webapp .

    - name: scan WebApp for CVEs
      uses: 'docker://aquasec/trivy:0.2.1'
      with:
        args: --exit-code 1 --severity HIGH,CRITICAL ${{ env.WEBAPP_TAG }}

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push WebApp dockerimage
      run: |
        docker push ${{ env.WEBAPP_TAG }}

    - name: push ConsoleApp dockerimage
      run: |
        docker push ${{ env.CLIAPP_TAG }}
