name: release

on: 
  push:
    branches:
    - master
    paths:
    - version

jobs:
  build-n-release:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set env vars
      run: |
        base_tag=$(cat ./version)
        webapp_tag="deepnetwork/image-scanner-web:$base_tag"
        cliapp_tag="deepnetwork/image-scanner-cli:$base_tag"
        echo "::set-env name=TAG::$base_tag"
        echo "::set-env name=WEBAPP_TAG::$webapp_tag"
        echo "::set-env name=WEBAPP_TAG_LATEST::deepnetwork/image-scanner-web:latest"
        echo "::set-env name=CLIAPP_TAG::$cliapp_tag"
        echo "::set-env name=CLIAPP_TAG_LATEST::deepnetwork/image-scanner-cli:latest"

        tests_tag="deepnetwork/image-scanner:$base_tag-tests"
        tests_dir="$HOME/testresults"
        echo "::set-env name=TESTS_TAG::$tests_tag"
        echo "::set-env name=TESTS_DIR::$tests_dir"

    - name: run unit-tests
      run: |
        docker build -t ${{ env.TESTS_TAG }} -f ./dockerfile --target testrunner .
        sudo mkdir -p ${{ env.TESTS_DIR }}
        docker run --rm --mount type=bind,source=${{ env.TESTS_DIR }},target=/app/testresults ${{ env.TESTS_TAG }}

    - name: publish test results
      uses: actions/upload-artifact@v1.0.0
      with:
        name: test_results
        path: '${{ env.TESTS_DIR }}/test_results.xml'

    - name: lint dockerfile
      uses: brpaz/hadolint-action@v1.0.2
      with:
        dockerfile: ./dockerfile

    - name: build ConsoleApp dockerimage
      run: |
        docker build -t ${{ env.CLIAPP_TAG }} -f ./dockerfile --target cliapp .
        docker tag ${{ env.CLIAPP_TAG }} ${{ env.CLIAPP_TAG_LATEST }}

    - name: scan ConsoleApp for CVEs
      uses: 'docker://aquasec/trivy:0.2.1'
      with:
        args: --exit-code 1 --severity HIGH,CRITICAL ${{ env.CLIAPP_TAG }}

    - name: build WebApp dockerimage
      run: |
        docker build -t ${{ env.WEBAPP_TAG }} -f ./dockerfile --target webapp .
        docker tag ${{ env.WEBAPP_TAG }} ${{ env.WEBAPP_TAG_LATEST }}

    - name: scan WebApp for CVEs
      uses: 'docker://aquasec/trivy:0.2.1'
      with:
        args: --exit-code 1 --severity HIGH,CRITICAL ${{ env.WEBAPP_TAG }}

    - name: Docker Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: push WebApp dockerimage
      run: |
        docker push ${{ env.WEBAPP_TAG }}
        docker push ${{ env.WEBAPP_TAG_LATEST }}

    - name: push ConsoleApp dockerimage
      run: |
        docker push ${{ env.CLIAPP_TAG }}
        docker push ${{ env.CLIAPP_TAG_LATEST }}

    - name: tag the repo
      uses: hole19/git-tag-action@master
      env:
        TAG: ${{ env.TAG }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG }}
        release_name: Release ${{ env.TAG }}
        body: 
        draft: false
        prerelease: true